version: '3'

services:
    my-server:
        build: ./
        container_name: tmp
    proxy-nginx: 
        image: nginx
        container_name: proxy
        ports:
          - 80:8080
        volumes:
          - ./06/nginx.conf:/etc/nginx/nginx.conf

